#!/bin/sh
value=`cat ../secret`
git pull https://mungert69:$value@github.com/Mungert69/NetworkMonitorScheduler
dotnet publish -c release 
docker compose build
docker push mungert/networkmonitorscheduler:0.0.1
