version: "3.8"

services:
  networkmonitor-dapr:
    image: daprio/daprd
    command: ["./daprd",
      "-app-id", "networkmonitor",
      "-app-port", "2052", # Same as Expose port of Dockerfile of the respective service
      "-components-path", "/components",
      "-log-level", "debug"]
    volumes:
      - ~/code/NetworkMonitor/components/:/components
    depends_on:
      - networkmonitor
    network_mode: "service:networkmonitor"
  networkmonitor:
    image: mungert/networkmonitor:0.2.1
    restart : unless-stopped
    ports:
      - 2052:2052
      - 2053:2053
    stop_grace_period: 2m
    depends_on:
      - mariadb
      - redis
    volumes:
      - ~/code/securefiles/appsettings-dev.json:/app/appsettings.json
      - ~/code/securefiles/https.pfx:/app/https.pfx
  mariadb:
    image: mungert/mariadb:0.1.3
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - ~/sqldata:/var/lib/mysql
    restart: always
    container_name : monitordb
    environment:
      MARIADB_USER : admin
      MARIADB_PASSWORD : Ac.0462110
      MARIADB_DATABASE : MonitorDB
  mariabackup:
    image: mungert/mariabackup:0.1.2
    user: "0"
    volumes:
      - ~/sqlbackup:/db
    restart: always
    container_name: monitorbackup
    environment:
      DB_USER: admin
      DB_PASS: Ac.0462110
      DB_DUMP_TARGET: /db
      DB_DUMP_FREQ: 1440
      DB_SERVER: monitordb
  networkmonitorreact:
    image: mungert/networkmonitorreact-local:0.1.12
    restart: always
    container_name : monitorfrontend
    ports:
      - 443:443
    volumes:
      - ~/code/FreeNetworkMonitor/public/runConfig-dev.js:/var/www/html/runConfig.js
      - ~/code/securefiles/server-freenetworkmonitor.crt:/etc/apache2/server.crt
      - ~/code/securefiles/server-freenetworkmonitor.key:/etc/apache2/server.key
  redis:
    image: redis
    ports:
      - 127.0.0.1:6379:6379
networks:
  default:
    name: monitornetwork

