version: "3.8"

services:
  networkmonitorprocessor-dapr:
    image: daprio/daprd
    command: ["./daprd",
      "-app-id", "networkmonitorprocessor",
      "-app-port", "2054", # Same as Expose port of Dockerfile of the respective service
      "-components-path", "/components",
      "-log-level", "debug"]
    volumes:
      - ~/code/NetworkMonitor/components/:/components
    depends_on:
      - networkmonitorprocessor
    network_mode: "service:networkmonitorprocessor"
  networkmonitorprocessor:
    image: mungert/networkmonitorprocessor:0.0.1
    restart : unless-stopped
    ports:
      - 2054:2054
      - 2055:2055
    stop_grace_period: 2m
    volumes:
      - ~/code/securefiles/appsettings-dev.json:/app/appsettings.json
      - ~/code/securefiles/https.pfx:/app/https.pfx
networks:
  default:
    name: monitornetwork
