# ./components-compose/redis-pubsub.yml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: rabbitmq-pubsub
  namespace: default
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: host
    value: rabbitmq:5672
  - name: maxLen
    value: 5

