# ./components-compose/redis-pubsub.yml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: default
spec:
 type: pubsub.rabbitmq
 version: v1
 metadata:
 - name: host
   value: "amqp://usercommonxf1:test12@rabbitmq:5672/%2fvhostuser"
 - name: durable
   value: true
